main: com.github.atomishere.rediscommunication.spigot.RedisCommunicationSpigot
name: RedisCommunication
author: AtomIsHere
version: 1.0.0
description: Two way communication with bungee and spigot using Redis's pub/sub abilities. - SPIGOT